[build-system]
requires = ["setuptools>=42"]
build-backend = "setuptools.build_meta"

[project]
name = "fastapi"
version = "0.1.0"
description = "My awesome Python project"
authors = [{ name = "Your Name", email = "you@example.com" }]
dependencies = []
