name: C/C++ CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y build-essential cmake pkg-config libopencv-dev

      - name: Create build directory
        run: mkdir cpp-streamer/build

      - name: Setup Cmake
        shell: bash
        working-directory: ./cpp-streamer/build
        run: cmake ..

      - name: Build Project
        shell: bash
        working-directory: ./cpp-streamer/build
        run: cmake --build .
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: pseudo test
      run: ls

  #containerize:
  #  runs-on: ubuntu-latest
    
  #  steps:
  #  - name: build container from image
  #    working-directory: ./cpp-streamer/
  #    run: docker build -t cpp_streamer_app .
  
  push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/cpp_streamer_app:latest
