name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Create build directory
      run: mkdir cpp-streamer/build

    - name: Setup Cmake
      shell: bash
      working-directory: .cpp-streamer/build
      run: cmake ..

    - name: Build Project
      shell: bash
      working-directory: .cpp-streamer/build
      run: cmake --build .
